
name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.17.6]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Docker build
      run: |
        docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
        docker build -t juan-crossfit-server .
        docker tag juan-crossfit-server rhkrgudwh/juan-crossfit-server:${GITHUB_SHA::7}
        docker push rhkrgudwh/juan-crossfit-server:${GITHUB_SHA::7}
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        envs: GITHUB_SHA
        script: |
          docker stop server
          docker image rm -f $(docker image ls -q)
          docker pull rhkrgudwh/juan-crossfit-server:${GITHUB_SHA::7}
          docker tag rhkrgudwh/juan-crossfit-server:${GITHUB_SHA::7} juan-crossfit-server
          docker run -d --rm --name server -p 80:3000 juan-crossfit-server
          docker cp /home/ec2-user/.env server:.