
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Docker build
      run: |
        docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
        docker build -t juan-crossfit-server .
        docker tag juan-crossfit-server rhkrgudwh/juan-crossfit-server:${GITHUB_SHA::7}
        docker push rhkrgudwh/juan-crossfit-server:${GITHUB_SHA::7}
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ec2-3-38-210-236.ap-northeast-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        envs: GITHUB_SHA
        script: |
          docker pull rhkrgudwh/juan-crossfit-server:${GITHUB_SHA::7}
          docker tag rhkrgudwh/juan-crossfit-server:${GITHUB_SHA::7} juan-crossfit-server
          docker stop server
          docker run -d --rm --name server -p 80:3000 juan-crossfit-server

